### ISSUE TITLE
Make a test that validates a bare bones config

### ISSUE THREAD

**Issue by SimonBiggs** [pymedphys/pymedphys#1119]
```toml
version = 1

[data_methods]
available = ["dicom", "trf"]
default_reference = "dicom"
default_evaluation = "trf"

[[site]]
name = "default-site-name"

    [site.export-directories]
    escan = '~/mudensity-demo/pdf'

[output]
png_directory = '~/mudensity-demo/png'

[gamma]
dose_percent_threshold = 2
distance_mm_threshold = 0.5
local_gamma = true
quiet = true
max_gamma = 5
lower_percent_dose_cutoff = 20
```
