### ISSUE TITLE
TRF to DICOM comparison and patient specific QA

### ISSUE THREAD

**Issue by fishdda** [pymedphys/pymedphys#989]
do we have the code for comparing mlc leaf positions between trf and plan dicom? or we should start from scratch.

**Comment by SimonBiggs** [comment]
Something like the following should do the trick:

```python
import pydicom
import pymedphys

trf = pymedphys.Delivery.from_logfile('path/to/logfile.trf')

ds = pydicom.read_file('path/to/dicom/plan.dcm', force=True)
dicom = pymedphys.Delivery.from_dicom(ds)

trf_mudensity = trf.mudensity()
dicom_mudensity = dicom.mudensity()

# etc ...
```

**Comment by fishdda** [comment]
yes, I tried several cases to compare the MU densities. Do you know the resources for these MU density difference? like MLC position error when delivery, or MU difference or anything else.
![0025_MU_diff](https://user-images.githubusercontent.com/23411165/90084841-084f7e80-dd49-11ea-89f2-f3eb066a2c69.png)

**Comment by fishdda** [comment]
Just the same issues from gamma analysis.  It would only give us a final 3mm/3% passing rate instead of pointing out the error sources. Do you have any idea for searching a better plan QA road?

**Comment by SimonBiggs** [comment]
It can be helpful to present MU Density differences per control point, and to potentially also plot jaw movement. See the following presentation:

http://www.simonbiggs.net/epsm2018

Some other talks on the topic:

* http://simonbiggs.net/iccr2019
* http://simonbiggs.net/eum2020

At the end of the day, we've found for patient specific QA, for a range of cases we can use this logfile method, as long as it also includes an independent dosimetric comparison (we use SunNuclear DoseCHECK). Without an independent dose calculation these logfile checks do not appear to be a sufficient verification.

It is worth noting that currently the majority of cases we still undergo direct dosimetric measurement with a 3D phantom (Scandidos Delta4). We decide which cases get measured, and which cases only get logfile + independent dose calc via an approach similar to NCS 22 and 24:

![image](https://user-images.githubusercontent.com/6559099/90086034-d2b49080-dd5c-11ea-89ee-cfb8346dcf35.png)

* https://radiationdosimetry.org/ncs/documents/ncs-22-cop-qaqc-imrt
* https://radiationdosimetry.org/ncs/documents/ncs-24-cop-qaqc-vmat

We've built a patient specific QA tool that can compare directly to Monaco, iCOM, DICOM, TRF, and Mosaiq SQL and it has been bundled within a GUI for use. That is that GUI that boots when you run:

```
pymedphys gui
```

**Comment by mchamberland** [comment]
@SimonBiggs actually, this looks like what I’m looking for!

I haven’t peaked at the source code yet, but does pymedphys provide functions to easily generate the plots? If not, care to share a Jupyter notebook? I am still learning Matplotlib...

**Comment by SimonBiggs** [comment]
Hi @mchamberland,

Actually, this is hopefully becoming easier and easier. We actually have a server web-app based GUI that we use at our centre to achieve this. The simplest way to get up and running with this tool is to first create the following config file located at `~/.pymedphys/config.toml` (where `~` is your home directory, for example `C:\Users\sbiggs`).

```toml
version = 1

[data_methods]
available = ["dicom", "trf"]
default_reference = "dicom"
default_evaluation = "trf"

[[site]]
name = "default-site-name"

    [site.export-directories]
    escan = '~/mudensity-demo/pdf'

[output]
png_directory = '~/mudensity-demo/png'

[gamma]
dose_percent_threshold = 2
distance_mm_threshold = 0.5
local_gamma = true
quiet = true
max_gamma = 5
lower_percent_dose_cutoff = 20
```

Then install the latest development release of pymedphys by running:

```
pip install pymedphys[user]==0.34.0-dev8
```

and then lastly, within a terminal run:

```
pymedphys gui
```

For more information on this tool check out the long thread on the mailing list:

https://groups.google.com/g/pymedphys/c/2LczVpmc_Ak/m/rXfCoZ0RAwAJ


Let me know how you go! :)
